"""user model update

Revision ID: 048b2e769281
Revises: 
Create Date: 2025-12-06 11:59:37.629067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '048b2e769281'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='sequelizemeta')
    op.drop_table('sequelizemeta')
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female'), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=True)
    op.drop_column('users', 'last_update')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'gender')
    op.create_table('sequelizemeta',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('name'), 'sequelizemeta', ['name'], unique=True)
    # ### end Alembic commands ###
