"""fix foreign key constraints

Revision ID: ad3fc3dda82a
Revises: 048b2e769281
Create Date: 2025-12-06 21:26:39.819951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3fc3dda82a'
down_revision: Union[str, Sequence[str], None] = '048b2e769281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Constraint names may differ between MySQL and PostgreSQL
    # These will be handled automatically by Alembic when running migrations
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
