"""fix foreign key constraints

Revision ID: ad3fc3dda82a
Revises: 048b2e769281
Create Date: 2025-12-06 21:26:39.819951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3fc3dda82a'
down_revision: Union[str, Sequence[str], None] = '048b2e769281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movie_collection_ibfk_1'), 'movie_collection', type_='foreignkey')
    op.create_foreign_key(None, 'movie_collection', 'movies', ['movie_id'], ['movie_id'])
    op.drop_constraint(op.f('movie_genre_ibfk_1'), 'movie_genre', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genre', 'movies', ['movie_id'], ['movie_id'])
    op.drop_constraint(op.f('movie_production_company_ibfk_1'), 'movie_production_company', type_='foreignkey')
    op.create_foreign_key(None, 'movie_production_company', 'movies', ['movie_id'], ['movie_id'])
    op.drop_constraint(op.f('movie_production_country_ibfk_1'), 'movie_production_country', type_='foreignkey')
    op.create_foreign_key(None, 'movie_production_country', 'movies', ['movie_id'], ['movie_id'])
    op.drop_constraint(op.f('movie_spoken_language_ibfk_1'), 'movie_spoken_language', type_='foreignkey')
    op.create_foreign_key(None, 'movie_spoken_language', 'movies', ['movie_id'], ['movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_spoken_language', type_='foreignkey')
    op.create_foreign_key(op.f('movie_spoken_language_ibfk_1'), 'movie_spoken_language', 'movies', ['movie_id'], ['id'])
    op.drop_constraint(None, 'movie_production_country', type_='foreignkey')
    op.create_foreign_key(op.f('movie_production_country_ibfk_1'), 'movie_production_country', 'movies', ['movie_id'], ['id'])
    op.drop_constraint(None, 'movie_production_company', type_='foreignkey')
    op.create_foreign_key(op.f('movie_production_company_ibfk_1'), 'movie_production_company', 'movies', ['movie_id'], ['id'])
    op.drop_constraint(None, 'movie_genre', type_='foreignkey')
    op.create_foreign_key(op.f('movie_genre_ibfk_1'), 'movie_genre', 'movies', ['movie_id'], ['id'])
    op.drop_constraint(None, 'movie_collection', type_='foreignkey')
    op.create_foreign_key(op.f('movie_collection_ibfk_1'), 'movie_collection', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
